### PR TITLE
Add nuked opn2 as alternative core

### PR DESCRIPTION
**Pull request by nukeykt**
Works only in msvc libretro backend now.

### CODE REVIEW

**Comment by ekeeke** [comment]
Looks quite good and clean, I like it.

Some suggestions before I can merge this:

1) make it configurable at build time as well (using a HAVE_YM3438_CORE macro for example) so it does not break other ports that do not have config.ym2612 and updated Makefiles for now

2) rename config.ym2612 to config.ym3438

You might also want to convert C++ comments into ANSI C ones as it seems that a few libretro platforms that can only use some very old MSVC compiler also need this.

Thanks.

**Comment by nukeykt** [comment]
Done

**Comment by ekeeke** [comment]
Some more things:

4) call sound_init() in libretro.c when config.ym3438 is changed to allow fm core hot swapping while game is running (with some potential sound issues but that would be expected) 

5) save config.ym3438 value when saving context and check saved value before loading fm instead of checking config.ym3438 since saved context could potentially differs from current config one. Obviously, there would still be sound issues when loading state if config differs but at least this would prevent nasty memory crashes (since ym2612 and ym3438 context size are likely different).

Thanks

**Comment by ekeeke** [comment]
Another thing: since you are running the chip at its original frequency (vclk/6 i.e 24x faster than MAME ym2612), it would make more sense to render interleaved channels samples as the original chip does (as opposed to summing all 6 channels in one sample every 24 update cycles ). 

Ideally we would also only write a new sample and advance fm_buffer when it's actually changed. This would require having a separate timer increment for blip_buffer in sound_update function (either 144×7 wirh your current implementation or 24×7 with my above proposal) but this would greatly reduce the needed size for fm_buffers.

What do you think ?

**Comment by nukeykt** [comment]
Multiplexed output produces very quiet audio (i think it could be fixed with amplifying output) and i'm not sure how it would work with the linear interpolation. I've also tried to update sample every 24 clock, but it produced clicks in output and caused missed/invalid register writes(It even somehow triggered loud PCM mode once). I couldn't fix this. The current implementation is seems to be good compromise.

**Comment by ekeeke** [comment]
Ok.

One last thing: in libretro.c, the idea would be to keep at least the call to sound_init so that fm core could still be swapped while playing the game (without reseting anything). Could be useful for comparing the fm cores for example in sound test. It would also make context saving always coherent of current fm core.

**Comment by ekeeke** [comment]
Also, please make fm_buffers size dependent of HAVE_YM3438_CORE macro do that ports which do not use it can keep memory use optimized.

**Comment by nukeykt** [comment]
Unfortunately without reset MAME core just crashes.

**Comment by ekeeke** [comment]
Indeed, it probably crashes because fm buffer pointer and cycle counters are out of limits.

**Comment by nukeykt** [comment]
Thanks!

**Comment by James-F2** [comment]
Hi nukeykt!
So is it going to replace the old OPN2 core in Genesis Plus GX?
Will we see this new nukedOPN2 ym3438 in the libretro core?

**Comment by ekeeke** [comment]
@James-F2: it's an alternate FM core to MAME one, it's not going to replace it as it's likely requiring more CPU processing, since it's running at FM internal clock instead of sample clock . To be honest, I don't think you would hear much difference as no commercial game's sound engine likely relies on sub-sample writes granularity, but it's still a great achievement and a nice thing to have in Genesis Plus GX.

@nukeyt: Thanks to you for your work. Have you considered posting the results of your researches on spritesmind forum ? I 'm sure there will be many people there interested by this.

**Comment by nukeykt** [comment]
> @nukeykt: Thanks to you for your work. Have you considered posting the results of your researches on spritesmind forum ? I 'm sure there will be many people there interested by this.
Maybe sometime later

**Comment by ekeeke** [comment]
Out of curiosity, is there anything new or incorrectly emulated in current implementations that you figured from die shot analysis? LFO in particular comes to mind, it was not 100% clear to me how much bits of FNUM are used and how exactly they are weighted.

Also, do you emulate pipelining and registers cycling as figured by Sauraen in spritesmind thread or are you just processing one operator at each cycle ?

**Comment by nukeykt** [comment]
> Out of curiosity, is there anything new or incorrectly emulated in current implementations that you figured from die shot analysis? LFO in particular comes to mind, it was not 100% clear to me how much bits of FNUM are used and how exactly they are weighted.

LFO uses top 7 bits of FNUM. Modulation value is a shifted sum of two shifted FNUM_HIGH values using tables. New FNUM value is FNUM*2 +- FM. As new FNUM value is only 12 bits, LFO can overflow it.
Here's my implementation
https://github.com/nukeykt/Nuked-OPN2/blob/5680d23dfb9a304215ddc274663ff49687d8f358/ym3438.c#L469

MAME core has some issues in EG implementation. Here's what i remember.
1) EG timer is 12 bit. Due to hardaware issue timer skips 0 value, resulting in a VERY subtle difference in EG speed.
2) MAME has bug in decay phase of  ADSR. It first advances EG level and then checks sustain level reach. Real hardware does opposite. This is issue when sustain level is 0.
3) If you start note with low attack rate and then set attack rate to max value during attack phase, EG will stuck on real chip. This behavior is not emulated in MAME core.

AFAIR, LSI Test functionality is not emulated in any other core.  Most of them are already was figured out by Sauraen.

Probably there are also some other differences here and there.

> Also, do you emulate pipelining and registers cycling as figured by Sauraen in spritesmind thread or are you just processing one operator at each cycle ?

Yes. I'm emulating chip's pipeline. That's why my code looks messy.

**Comment by nukeykt** [comment]
Do you know what's difference between ASIC and discrete variants of the YM3438? The only thing i know is that status can be read from any port on the ASIC variant.

**Comment by p1pkin** [comment]
thanks for explanations, but 2. bug actually not present in MAME-based YM2612 cores like the one in GenPlusGX. there is check in Attack phase - if sustain level  == 0 then skip decay and go directly to sustain phase. however you provided good explanation why this quirk was needed at all.

**Comment by nukeykt** [comment]
Ok, i've missed that check.

**Comment by ekeeke** [comment]
Yes, 2. and 3. correct were fixed in GPGX YM2612 core then backported to MAME some years ago, see
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/sound/ym2612.c#L651
&
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/sound/ym2612.c#L986

As for 1., I am not really sure how EG counter bitwidth would have any impact since it is masked anyway through the EG rate shift values (largest mask being 0x7ff). I am not sure either what does 'skipping value 0" exactly means?

Regarding differences between ASIC-integrayed and discrete version, I have no idea besides the one you mentionned (actually I thought it was only the busy flag that could only be read from address 0 on discrete YM2612, and that timers flags could be read from anywhere). I don't think anyone has decapped the various MD2 ASICs yet.

**Comment by ekeeke** [comment]
Old Microsoft compilers do not support C99 specific types (I assume it's that outdated compiler for Xbox toolchain once again).

That's obviously an issue with your build environment that is normally under your responsibillity: for example, replace inttypes.h by stdint.h and copy following file in your build environment:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro-common/include/compat/msvc/stdint.h

**Comment by nukeykt** [comment]
After 4095 counter value next is 1. Zero is skipped as carry flag is not cleared. Also this explains odd increment pattern for 0-7 rates: it requires at least 11+3=14 bits.

**Comment by p1pkin** [comment]
@ekeeke 
> As for 1., I am not really sure how EG counter bitwidth would have any impact since it is masked anyway through the EG rate shift values (largest mask being 0x7ff). I am not sure either what does 'skipping value 0" exactly means?

I think it will be easier to explain using Exodus YM implementation.
1st part, EG cycle counter bit width explanation:
look at this code: https://bitbucket.org/exodusemulator/exodus/src/ceac297d914fc0d5f2b10225dbb89d56be4ebbe5/Devices/YM2612/YM2612.cpp?at=default&fileviewer=file-view-default#YM2612.cpp-1965
and this table: https://bitbucket.org/exodusemulator/exodus/src/ceac297d914fc0d5f2b10225dbb89d56be4ebbe5/Devices/YM2612/YM2612.cpp?at=default&fileviewer=file-view-default#YM2612.cpp-32

as you may notice table have non-consistent increment entries for rates 2, 3 and 7 based on Nemesis's hardware measurements. why this happen ? - because of envelopeCycleCounter in hardware is 12 bit only. as result at rates 2 and 3 counterShiftValue will be 11 and after cycle counter shift will left only 1 bit -> from table record {0,1,1,1,0,1,1,1} will be read only first two values, 0 or 1.
same in rate=7 case - counterShiftValue=10 -> after cycle counter shift will left 2 significant bits -> from {0,1,1,1,1,1,1,1} will be read only idx 0-3 values.

so, everything shows envelopeCycleCounter each  3rd sound sample  incremented in the way
envelopeCycleCounter++; if (envelopeCycleCounter == 0x1000) envelopeCycleCounter = 0;
However! several years ago I've seen results of YM logic analyzer recordings precise analysis/research made by one Russian guy, which shows full range of envelopeCycleCounter values is not 0x1000 but 1 cycle less. so, basically it skips 0xFFFF or 0 value (I wasn't sure which one), as was said by @nukeykt in harware it is 0 value. so, cycle increment seems works like:
envelopeCycleCounter++; if (envelopeCycleCounter == 0x1000) envelopeCycleCounter = **1**;
the difference is very very not significant, but anyway glad to see it was approved by die decap RE.

**Comment by joepogo** [comment]
Ahh yes. I keep forgetting that. :/ Thanks eke. I added stdint.h and was able to get it to compile. I only had to move 

Bit8u direction = 0;

To the top of the function just after the opening bracket..

void OPN2_EnvelopeSSGEG(ym3438_t *chip)
{
Bit8u direction = 0;

I am assuming the retroarch original Xbox port might have to do the same to get it to compile just for reference sake. Otherwise, thanks for answering and thanks for adding this to the core nukeykt.

**Comment by ekeeke** [comment]
@nukeykt / @p1pkin : thanks for the detailed explanation, it indeed makes perfect sense now and I see what you mean with counter value 0 being skipped. 

So basically, for rate values 0-3, envelope increment cycle loops after 1 and for rate values 4-7, it loops after 3, instead of going up to 7 as it theoretically should. This indeed explains the differences observed by Nemesis but also probably means Jarek's table was actually correct (I guess it was figured from another OPN chip where envelope counter is 14-bit). Except maybe for rate values 0 and 1 where it should be {0,0,0,0,0,0,0,} according to Nemesis tests but was {0,1,0,1,0,1,0,1} in MAME. 

Btw, I see that those "fixes" were actually not backported in MAME's fm.cpp.

**Comment by James-F2** [comment]
REPORT;  
Nuked-OPN2 has a bug with vibrato, while Mame core plays correctly.

Test track (BGM 06, in game):
https://www.youtube.com/watch?list=PLEeAvoMXmmr8gWufIBtTcIbWqRD-7H5Pv&v=_VQz2ZPbltw

**Comment by nukeykt** [comment]
I don't see any problem with implementation. Have you reset game after switching emulator?

**Comment by James-F2** [comment]
Of course I have reset the emulation.
Implementation? A simple audio test and you'll hear that the vibrato has much less range with Nuked-OPN2 compared to the hardware.

**Pull request merged**
