### PR TITLE
[Core/Sound] Nuked OPN2: removed discrete ym3438 core

### PR DESCRIPTION
**Pull request by nukeykt**
Apparently YM3438 on Sega TeraDrive behaves and sounds exactly like ASIC one, so there's no more point to have this option anymore.

### CODE REVIEW

**Comment by ekeeke** [comment]
@nukeykt : from what I understand, there is still a difference between ASIC and discrete YM3438 regarding status read on 'invalid' port (ASIC version allowing reads from any ports anytime) so technically Tera Drive and MD2 should behave (and possibly sound) differently for the few games that read from invalid ports (Hellfire, Earthworm Jim).

**Comment by nukeykt** [comment]
Actually Sega fixed this issue using two AND gates. These gates set A0-A1 pins state to low when z80/m68k try to read chip's status, effectively making it equivalent to ASIC YM3438.

**Comment by ekeeke** [comment]
I see, thanks for the clarification.

**Comment by villahed94** [comment]
Actually the behaviour depends upon the bus arbiter. Using a YM2612 in a VA7 MD1, VA0-1.8 MD2 or VA3 MD2 results in a bus behaviour similar to that of the ASIC'd YM3438, but has typical YM2612 sound.

**Comment by nukeykt** [comment]
How did you wired it? Possible ASIC one is still outputs status.

**Comment by villahed94** [comment]
I wired it like this:
Z80 D0-D7 -> YM2612 D0-D7
Z80 A0,A1 -> YM2612 A0,A1
YM2612 /IC -> Pin 58 of the 315-5660 ASIC. (/SOUND).
(315-5660 pinout) : https://i.imgur.com/fZqxWRB.png
https://i.imgur.com/rW85B5a.png

**Comment by nukeykt** [comment]
Thanks. So YM3438 still functional then? If yes, both chips will respond on IO request resulting in bug free music on EWJ. BTW i think such bus conflict can damage chips, so i'd recommend to make YM2612 write only(i.e wire YM2612 /RD to +5v)

**Comment by villahed94** [comment]
Yes, the ASIC YM3438 is still functional after installing the YM2612. No bus conflicts whatsoever and it's bug free. However I will try your suggestion of making one of the chips read only.
 Corrected video: https://www.youtube.com/watch?v=QDZtrMkUv4E

**Comment by villahed94** [comment]
Yes, the ASIC YM3438 is still functional after installing the YM2612. No bus conflicts whatsoever and it's bug free. However I will try your suggestion of making one of the chips read only.
 Corrected video: https://www.youtube.com/watch?v=QDZtrMkUv4E

**Pull request merged**
