### PR TITLE
Sync both repos

### PR DESCRIPTION
**Pull request by twinaphex**
I think both repos should be in sync after this PR.

### CODE REVIEW

**Comment by ekeeke** [comment]
I think it's missing the last PR that fixes CHD file loading crashes in Retroarch.

Also, what is weird is that both repros still don't appear in sync in github and if I try to merge within my repository, I get all the same commited  files marked as changed again (plus some of my own commits that were cherry-picked into libretro repository and now appears as different commits than mine and changed files although they are identical to my base). Not sure what you did but it seems like github sync between the two repositories is completely fucked :-( 
How do we solve that?

**Comment by KMFDManic** [comment]
I was wondering why the Build I grabbed was being weird.  This would explain it.  pce-fast & fx work great for chd support, thus far.  Looking forward to testing the proper implementation within Genesis Plus GX. Great work!

**Comment by twinaphex** [comment]
@ekeeke Well I could nuke the current fork we have and reclone, however, the issue then is that we'd lose the Github issues. Unless we either close them or transfer them.

**Comment by ekeeke** [comment]
I ended up forcing merge myself on my side despite all the false file changes indication. I needed to pick the first (default) merge option to get finally in sync with libretro github. Strangely, commit associated to pull request only showed really modified files time (there were apparently a few ones that you missed in your previous PR (see https://github.com/ekeeke/Genesis-Plus-GX/commit/6fddc326661491473be992a5f85f0069c44c572b)

I think the problem is that all merge from my repo to libretro should have been done through github interface or at least using the same options as github default merge if you are using command line (see https://help.github.com/articles/about-pull-request-merges/).

**Pull request merged**
