### PR TITLE
Update Nuked-OPLL sound core to upstream

### PR DESCRIPTION
**Pull request by crashGG**
Update Nuked-OPLL sound core to latest 1.02 upstream

### CODE REVIEW

**Comment by ekeeke** [comment]
Sorry but I can't merge GPL code with non-commercial code, it needs to be licensed under LGPL like latest versions of Nuked OPN2 core or dual-licensed for use in this emulator with the same non-commercial license, as Nuked did with initial version (see https://github.com/ekeeke/Genesis-Plus-GX/commit/dd6165785f321a8dd3d2de89cbe638a70dc6286e )

**Comment by crashGG** [comment]
I don’t know how to modify the license . 1.0-1.02 has made a lot of upgrades and fixes. after compiled it runs fine.

**Comment by ekeeke** [comment]
Only copyright owner(s) can change the license.

From what I can tell, the only important change is that commit, which apparently fixes some edge case on channels 8 & 9 (and might not be noticeable in any Master System games with FM support):
https://github.com/nukeykt/Nuked-OPLL/commit/1269cf5a783b65583b50fa2464d08be75830aaa0

The rest is addition of support for different kind of OPLL chips  which is not applicable to this emulator as we only use YM2413 chip support for Master System and minor code refactoring without any functional impact.

**Comment by ekeeke** [comment]
Closing this for aforementionned reasons. I will rather backport the latest commit from nuked (other commits having no functional impact for Master System emulation), there is already an user request fo this (see issue #532)

**Pull request closed without merging**
