### PR TITLE
[libretro] added mono output option + YM3438 compilation fixes

### PR DESCRIPTION
**Pull request by ekeeke**

### CODE REVIEW

**Comment by James-F2** [comment]
@ekeeke 

ekeeke, do you think you can add second-order lowpass filter to GPGX so that Model2 console owner can enjoy accurate sound from GPGX?
I will find the correct frequency (Lowpass % in GPGX) value to a Model2.

**Comment by ekeeke** [comment]
This has been on TODO list for quite some time (aside providing accurate emulation of FM status reads and DAC differences between the two models) but it's not really a priority to me. Even if that's only a single order low-pass filter, it can be configured by users to get a more filtered sound experience and surely the frequency response difference are way too minor to make it an unenjoyable experience.

**Comment by James-F2** [comment]
Aaa you're right, the difference is not that big.
Model1 sound is more sought after anyway.

As for the DAC difference with quantization noise, Streets of Rage 2 - BGM 10 is perfect to test this.
I keep the "YM2612 DAC Quantization" On all the time.

**Comment by ekeeke** [comment]
DAC quantization is a different thing, it just reduces FM channels output resolution to 9-bit as the real chip does (well, not exactly since, on real chip, it is done on FM operator output before accumulating them into channel output... that's another thing on that longTODO list) and works the same on discrete ("MD1") or ASIC-integrated ("MD2") chip versions.

The DAC difference is indeed that noise that happens on discrete YM2612 at low volume. This is what some people call "ladder effect" effect: it happens on analog output after the DAC generated voltage from FM digital samples. Basically, the step between center ("0") level and negative sample values is much larger than expected because of the DAC technology being used (array of resistors that either pulls down voltage from Vcc or pulls it up from ground but does not meet exactly at Vcc/2)

**Pull request merged**
