### PR TITLE
Add support for Shi San Zhang Ma Jiang: Zhong Guo Mei Nv Pian copy protection

### PR DESCRIPTION
**Pull request by techmetx11**
Fixes the copy protection mapper not being supported for this recently-dumped unlicensed game

### CODE REVIEW

**Comment by ekeeke** [comment]
Thanks for your contribution.
Just one remark: since the mapper seems identical to the one used in several other taiwanese games (777 Casino, Soul Blade, Elf Wor, etc), could you move the database entry for this game with the other ones ? Also, are you sure this one only checks one address ($400004) annd there aren't other checks at the other usual addresses ($400000, $400002 and $400006) elsewhere in the game ? It might be safee to add the other addresses with same register values as in other games.

**Comment by techmetx11** [comment]
I've reverse engineered the game, and it does seem to only check from $400004 (by storing the VDP control port address in $FF4020, AND'ing the upper word half with $4F to produce $400004, and reading from it), though it wouldn't hurt to add the other addresses just in case

**Comment by ekeeke** [comment]
You can add in comment for this game that only address $400004 seems to be used and others are guessed from other dimilar games, like I did for 777 Casino.

**Comment by techmetx11** [comment]
That sounds good, I'll do that (and move the entry closer to the Taiwanese unlicensed games)

**Pull request merged**
