### PR TITLE
Nuked OPN2: ASIC YM3438 & YM2612 emulation (Experimental)

### PR DESCRIPTION
**Pull request by nukeykt**

### CODE REVIEW

**Comment by ekeeke** [comment]
It should also have a single config.ym3438 where 0 means MAME core and 1-2-3 corresponds to each possible configuration of your ym3438 core.

**Comment by ekeeke** [comment]
You should also revert the following declaration in ym3438.c

`void OPN2_Reset(ym3438_t *chip, Bit32u type)`

**Comment by ekeeke** [comment]
Also, could you explain a little bit how you are emulating ladder-effect for discrete YM2612?

 It seems like you are shifting zero and positive value up by one (I guess it has the same effect on sound than shifting down negative values down by one i.e amplifying the gap between 0 and -1 steps but I'm not 100% sure).

It also seems like you are fixing output at +1 when left/right channels are muted (not sure why you bothered doing these calculations with sign value considering it will initially be 0 then incremented by one for positive values and 1 for negative values so final result will always give +1 in both cases).

**Comment by nukeykt** [comment]
Yes

**Comment by nukeykt** [comment]
Yesterday i did some test on hardware with YM2612/YM3438 in PCM debug mode. And noticed that there's almost no distortion(negative part was shifted by 1 in both cases). So i assumed that distortion comes from the silence gaps between samples(YM2612 outputs sample every 4th internal clock and in PCM test mode(0x2c register) there's no gaps). Setting them to the sign value gives heavier distortion(negative part will be shifted by 7).

Arithmetic shifting sample by 8 will result on -1 for negative and 0 for positive. I shifted non negative sample by 1 to match hardware tests.

**Comment by ekeeke** [comment]
Not still sure to fully understand your DAC implementation in regard to what you are describing, I will have to take a look later...

**Comment by James-F2** [comment]
I see there have been a lot of changes to Nuked-OPN2, I have some questions to you @nukeykt .

1. Do you have all hardware variants of the YM2612/YM3438 that you emulated?
2. Is the DAC the the primary difference between the variants?
3. Did you accurately emulate the noisy discrete YM2612 DAC?

Thank you.

**Comment by nukeykt** [comment]
1. I have discrete YM2612 and YM3438.
2. My core is based on discrete YM3438. ASIC YM3438 is should be almost like discrete one except a bit improved DAC and ability to read status from any port. I have no idea about other differences between YM3438 and YM2612. There was rumors that discrete YM3438 has incopatible timers. But i think it's due to bad YM3438 connection as TeraDrive(has discrete YM3438) and my core don't suffer from this bug.
3. I have no idea how it's accurate. That's why it's experimental

**Comment by James-F2** [comment]
> I have no idea how it's accurate. That's why it's experimental

I have a good audio setup in my home studio for critical audio listening tests, and various VST plugins to measure frequency response and noise floors, etc.
I can test the current discrete YM2612 code in comparison to a Model1 VA6, but I need a test build.
Can you please compile a test built?

**Comment by nukeykt** [comment]
Here's test build
https://drive.google.com/file/d/0B4n8cpbZ9qicQ1JQNHc5LW9odEk/view?usp=drivesdk

**Comment by James-F2** [comment]
I am sorry but I have to be blunt,, HOLY SHIT !!
That Nuked-OPL2 YM2612 'ladder effect' noise is so accurate I can't believe you actually did it!
This is really exciting moment in time because OPN2 emulation has never been that accurate including it's hardware bugs and distortions.
Fantastic job once again nukeykt!

**Comment by James-F2** [comment]
Here are some examples where there is clear difference.
In the archive I included My Model1 VA6 recording and all OPN2 core variants.
http://www.mediafire.com/file/ukghe79ktyqtysr/OPN2_Cores_Comparison.7z

Aladdin: listen for intro noise and 16sec note stops tail quantization.
Konami Logo: listen for music end tail quantization noise.

**Comment by James-F2** [comment]
@nukeykt 

Here are some videos where the timing bug of the YM3438 appears:
https://www.youtube.com/watch?v=8hqVWYwbZH8
https://www.youtube.com/watch?v=VBEkqSqgOL8

**Comment by ekeeke** [comment]
@James-F2 : there is nothing we can do about this, the cores each have their own state and switching them while in game will reset the state of FM chip but not the game who configured it initially. You have to entirely restart the game to avoid this but it can still be useful in sound tests where the game reconfigures the chip when you restart a sound effect or tune.

@nukeykt : I think I finally got it, was making a mistake with the sign value. It is actually equal to -1 for negative sample value, +1 for positive ones. So the offset is actually {+1,+1,+1,+1-} = +4 for positive channel samples (channel output being the sum of each 4 cycles outputs) and {0,-1,-1,-1} = -3 for negative one, giving a gap between 0 and -1 levels which is 7x larger than normal

Also, it seems that when the stereo channel is muted (lock_l=0 or lock_r=0) , output is still oscillating between -3 and +4, resulting in slightly noriceable noise. Is that something you observed ?

**Comment by nukeykt** [comment]
@James-F2 thanks for testing. Glad to hear that results are match with hardware.
@ekeeke Unfortunately my YM2612 schematic is very noisy, so i couldn't check it. Will be very nice if somebody can check it.

**Comment by ekeeke** [comment]
According to this post, it seems to actually be the case indeed
http://gendev.spritesmind.net/forum/viewtopic.php?f=24&t=1402&start=21

Probably related to how MOL/MOR analog outputs are muted (DAC output is pulled down or up to Vcc/2 so it's possible middle point is again not exactly reached)

**Comment by nukeykt** [comment]
I've looked at YM2612 DAC schematic. Indeed my code is seems to be correct.
Depending on sign bit matrix is connected to either VCC or GND. At left side we have DAC output. At the end of matrix we have maximum resistance which is equivalent to +1 or -1 on PCM. Then depending on cycle and R,L masks, output connected either to DAC output or +1,-1.
ym2612 dac

**Comment by ekeeke** [comment]
Interesting (I also love how you managed to analyze the schematic so quickly, I personally always thought the DAC output was on the right side of the matrix lol).

So basically it's supposed to output Vcc/2 ( 0 ) when DAC output is muted (either when channel is muted or during non-duty cycles) but because of additional resistor it ends up outputing either +1 or -1 based on sign bit, which results in some low noise being played on top ?

But then, where does the +1 offset on DAC output cycle in your implementation when channel output is positive ? Matrix output imperfection which cause positive  and negative parts not meeting exactly at the middle point (Vcc/2) ? What exactly happens in matrix when channel 9-bit output is 0x0 or 0x100 i.e none of matrix input lines is asserted ? Theoretically, it should output Vcc/2 for 0x0 and GND for 0x100 so isn't rather the matrix connected to either Vcc/2 (when sign bit is 0) or GND (when sign bit is set) ? Therefore, it would rather be the negative side being too far from Vcc/2 when it reaches 0x1ff and a negative offset that need to be applied when sign bit is set rather than the opposite ?

**Comment by nukeykt** [comment]
Sign variable in my implementation is +1 or -1 depending on channel's output MSB bit, i also increase channel's output by 1 if it is not negative. Matrix is indeed imperfect as shown by hardware tests using "loud PCM" bit set: gap between 0 and -1 levels is 2x more than should be. That's why i increase non negative value in my implementation.
In YM2612 channel's output LSB bits are XORed by sign bit(i.e inverted for negative value).
So for 0x00 we have maximum resistance and output is nearly VCC/2. For 0x100 we should invert LSB bits. So matrix input value is 0xff(minimal resistance), thus output is GND.

**Comment by p1pkin** [comment]
@nukeykt any chances someone put an eye at sample-based Yamaha chips ? like YMW258F/YM278B/YMF292F/AICA series :)
that's the main reason why I'm here - they are not that good researched as YM2612, but clearly share some component's logic like EG or LFO.

**Comment by ekeeke** [comment]
@nukeyt: thanks for the explanation, I think I now understand better how DAC is working. So, for -1 (0x1FF), resistance value ends up the same as with 0 i.e maximum and output is also nearly Vcc/2 (but slightly below while 0 was slightly above) ? I am still not sure though to conceptualize how you can have voltage increasing from 0V (GND) to Vcc/2 by increasing a resistance value, my electronic knowledge is a little bit limited and rusty.

**Comment by nukeykt** [comment]
@p1pkin I doubt i'll emulate these chips. Here's my objections:
1) I have no experince with these chips. YMF262 and YM3438 are very known chips as they were used on popular systems.
2) Interfacing these chips is harder than FM chips as they require additional chips.
3) No die shots are available. Thus a lot of hardware tests should be performed to extract internal work knowledge.

@ekeeke Yes. I think it is similar to pull up/down resistor.

**Comment by p1pkin** [comment]
@nukeykt 
1. YMF292F = Sega Saturn "SCSP", AICA = Sega Dreamcast Yamaha AICA, besides of quite popular home consoles both was used in number of popular arcade systems, so these sound processors was popular as well.
at logic level they use very similar attenuation calculation part - 10bit AEG value summed with "Total Level" register, ALFO. then (supposedly) converted to linear multiplier form and applied to signed 16bit sample. this sample does to mixer adder (unlike 262/3438, all 32/64 channels digitally mixed together and result output at 44100Hz rate to DAC), and DSP input buffer (which may be read by host CPU and used for test research measurements).
they are different in little details but in general have many similarities, for example research done by MSX-fans shows YM278B (used in MSX "Moon Sound" board) uses same step tables/principles as earlier FM chips like 3484.

2. Interfacing to PC is hard indeed. but its possible to interface lets say Dreamcast to PC via serial cable, boot from Dreamshell disk, write some test/probe code at C and compile it using Kalisti SDK, upload to console via serial, run and get back probing results.

3. right, it is sad fact. but we are working on it, perhaps in not far feature my fellows will have some spare time for AICA and SCSP decapping.

**Pull request merged**
