### PR TITLE
Re-syncing with libretro repo

### PR DESCRIPTION
**Pull request by twinaphex**
Let me know if this PR is too messy for you, if so you might have to manually merge or something.

### CODE REVIEW

**Comment by twinaphex** [comment]
BTW ekeeke, we might need your advice -

http://buildbot.libretro.com/web/

We currently have the Genesis Plus GX core running inside the RetroArch Web Player, but the graphics are distorted. I am not sure why. 

http://imgur.com/a/QTIX7

It looks like this. This is the Emscripten core.

**Comment by ekeeke** [comment]
Huh, that's weird. Seems like every 8th pixel is rendered incorrectly. Are you sure core rendered screen is displayed untouched (no post processing, filtering or shader applied) ? 

Do you have other games screenshots (preferably ones with no black background), do they all look the same ?

Have you tried with -DALIGN_LONG option set in emscripten Makefile defines to see if this makes any difference ?

**Comment by twinaphex** [comment]
I'll try ALIGN_LONG and then report back.

**Comment by ToadKing** [comment]
The issue with the emscripten bug was two things:

1. It needed ALIGN_LONG defined, no unaligned memory access with emscripten.
2. Emscripten packs data as compact as it can, so the RAM/VRAM/etc. byte arrays were not aligned on word boundaries. Right now we're working around it with `__attribute__` but perhaps you have a better way to do it, such as defining the arrays as uint32 instead of uint8.

**Comment by ekeeke** [comment]
I see.

Redefining arrays would require to rewrite a lot of the code and could make things less optimized when dealing with array indexes, it would be simpler (and better) to force alignment in the compiler if that is possible. Problem with __attribute__  is that it is not compatible with MSVC compilers from what I remember from previous libretro porting discussions but maybe macros could be used like for inlining.

Have you run the compiler with "-s SAFE_HEAP=1" to show all alignment issues and arrays that really need to be aligned on short or long word boundaries ? In VDP, only a few are accessed as long word from what I remember (only vram[] and vsram[] I think). while cram[] and sat[] arrays are accessed as short words and bg_name_xx[] are always accessed as byte. There are also potential problems with other arrays in the core that are used to run 68k code from (like work_ram ( ), boot_rom[], cart.rom[), etc) since access can be made as byte or as short words. Maybe more so this could quickly become a hassle and quite dirty to force alignment for all of them in the code.

**Comment by p1pkin** [comment]
there is standard C++11 feature for this http://en.cppreference.com/w/cpp/language/alignas (in MSVC supported starting from VS2015)
why use some custom GCC attributes instead ?

**Comment by twinaphex** [comment]
Because this is a C-based project, and bumping it up to C++11 would be extremely undesirable.

**Comment by twinaphex** [comment]
@ekeeke @ToadKing We have this in libretro-common -

https://github.com/libretro/libretro-common/blob/master/memmap/memalign.c

Maybe this could be used or some derivative of it

**Comment by ekeeke** [comment]
@twinaphex: I am not going to switch static arrays into dynamically allocated arrays just because of misalignment issue with a specific compiler, sorry.

The only viable solution for me would be to add ATTRIBUTE_ALIGN(4) informations for every arrays that are known to be accessed using memory pointers with ATTRIBUTE_ALIGN macro defined somewhere (in libretro makefile or/and in macros.h) for different compilers.

I would although prefer not touching the code at all since this is pretty much a restriction imposed by a specific compiler that is useless for pretty much everything else. By default, most compilers (gcc/clang do it for sure but I believe MSVC does it as well) will align array for the platform largest data size if no attribute is specified so maybe there is an option in emscripten that gives the same behavior. If not, maybe it's possible to ask for such a feature to be implemented in their compiler ?

**Comment by ToadKing** [comment]
This was happening even with no optimization (`-O0`) and appears to just be something emscripten and/or fastcomp-clang does. And unless something in the C spec specifies arrays must be on a certain alignment I think it would be smart to not assume they are in the code.

**Comment by ekeeke** [comment]
Could you try to remove the forced alignment attributes but simply move declaration of 

```
uint8 sat[0x400]; /* Internal copy of sprite attribute table */
uint8 vram[0x10000]; /* Video RAM (64K x 8-bit) */
uint8 cram[0x80]; /* On-chip color RAM (64 x 9-bit) */
uint8 vsram[0x80]; /* On-chip vertical scroll RAM (40 x 11-bit) */
uint8 reg[0x20]; /* Internal VDP registers (23 x 8-bit) */
```

after

`uint32 dma_length; /* DMA remaining length */`

in vdp_ctrl.c


and

```
/* Cached and flipped patterns */
static uint8 bg_pattern_cache[0x80000];

after 

```
/* Output pixel data look-up tables*/
static PIXEL_OUT_T pixel[0x100];
static PIXEL_OUT_T pixel_lut[3][0x200];
static PIXEL_OUT_T pixel_lut_m4[0x40];
```

in vdp_render.c

then try to recompile  with -s SAFE_HEAP=1 and test the core see if alignment errors are naturally fixed this way.

Indeed, it seems you only needed to force alignment of these arrays but there are others that are accessed through uint32 pointers (linebuf for example) which does not have alignment issue so I suspect the order of declaration can have some effect, pretty much like having a uint32 in a struct force the alignment to 32-bit force every elements.

**Pull request merged**
