### PR TITLE
Added SDL2 build, cleaned up original SDL build, and added 32MB ROM support to both

### PR DESCRIPTION
**Pull request by Clownacy**
Ran into a problem with alloca in libtremor. Not sure if this makes a difference on other platforms. (EDIT: It broke MinGW)

To be honest, I have been getting the occasional segmentation error when closing the program, but I believe this is also a problem with the original SDL port (terminal never resumes, not allowing user input).

### CODE REVIEW

**Comment by ekeeke** [comment]
Is it really required to duplicate all those files under /sdl and /sdl2?
What are the differences?
If possible, it would be better to keep everything under /sdl and use #define and #ifdef for SDL2 specific code.

**Comment by Clownacy** [comment]
SDL2 changed a fair bit of its API. They even have [an entire guide](https://wiki.libsdl.org/MigrationGuide) for migrating. I tried to keep the current port as close to the old SDL1.2 logic as possible, but if someone tried to steer the port in a more SDL2-driven direction (hardware rendering, for one, to enable window upscaling) there'd be a lot more '#ifdef's.

Without a diff, the commit really doesn't show it, but a lot of constants and functions were renamed, too, including the keyboard-related ones, and I don't know if making an abstraction layer _for_ an abstraction layer would be the best approach.

As for differences, SDL1 has simply become deprecated, and SDL2, while dropping support for legacy platforms, adds support for multiple windows (good for users who want to expand the program by adding a debugging window for instance), and the Android platform, along with an associated touchscreen API. It also introduces the aforementioned hardware acceleration, which may come in handy for any future port of the Wii GUI. I think it just has more potential.

**Comment by ekeeke** [comment]
I don't know, I really don't like having these separated directories with duplicated files, it would be better (and easier to maintain) to have everything under a single /sdl directory, I'm sure this is possible. And if sdl is deprecated then makes sdl2 the default. I don't recall there was this much sdl api functions in main.c but even if it's too complicated, you could still have main_sdl.c and main_sdl2.c under the same directory and have makefile picking the right one.

As for your changes in libtremor headers, there are big chances it breaks other compilers / platforms as well, this kind of platform-specific include is therefore better to be put in osd.h when possible or only included if sdl2 pragma are defined. What is the problem with alloca anyway? I never heard about compilation issues with libtremor before.

**Comment by Clownacy** [comment]
Sorry for the wait, got caught up with a few other things.

Never thought of only duplicating individual files. Now SDL version-specific files are included in their own sub-folder, and depending on the Makefile selected, a different folder is included and processed.

The issue with alloca is that, for some reason, it doesn't exist on certain platforms. It's merged into some other header file. In the case of the Linux version I'm running, alloca.h actually exists, and so libtremor needs it to be included. That HAVE_ALLOCA_H is helpful, though. I now have the Makefile set it if it detects a non-Windows platform. I imagine a more thorough way is to use an automake system, but I wouldn't know the first thing about that.

**Comment by ekeeke** [comment]
Seems fine to me now, thanks a lot for your contribution.

**Pull request merged**
